virtual_modifiers:
  - CapsLock
keymap:
  - remap:
      CapsLock-h: Left
      CapsLock-j: Down
      CapsLock-k: Up
      CapsLock-l: Right
      CapsLock-e: Enter
      CapsLock-w: KEY_DOT
    mode: default
    device:
      only: ['dev/input/event14', '/dev/input/event4']
default_mode: default
