

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.bright]
black = "#666666"
blue = "#1118f0"
cyan = "#70c0b1"
green = "#3deb34"
magenta = "#c397d8"
red = "#b51929"
white = "#eaeaea"
yellow = "#e7c547"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.normal]
black = "#111111"
blue = "#4a4ec2"
cyan = "#5ae8e1"
green = "#3deb34"
magenta = "#b8bdfc"
red = "#d40b0e"
white = "#c5c8c6"
yellow = "#fff642"

[colors.primary]
background = "#111111"
foreground = "#c5c8c6"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[terminal.shell]
program="/home/lj/.cargo/bin/zellij"

[font]
builtin_box_drawing = true
size = 12.25

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[[mouse.bindings]]
mouse = "Right"
action = "PasteSelection"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control | Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "O"
mods = "Control"

#[[keyboard.bindings]]
#action = "ScrollHalfPageDown"
#key = "P"
#mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
opacity = 0.9
startup_mode = "Windowed"
title = "Alacritty"


[selection]
save_to_clipboard = true

[general]
live_config_reload = true
working_directory = "/home/lj"

[terminal]

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
